services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  mysql:
    container_name: ms_mysql
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      microservices-net:
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mysql: