POST http://localhost:8080/api/v1/employees
Content-Type: application/json

{
  "firstName": "Hemant",
  "lastName": "Kumar",
  "email": "hk123@gmail.com",
  "phone": "1010109090",
  "dob": "31-01-1999",
  "gender": "male",
  "city": "motihari",
  "state": "bihar",
  "pinCode": "845432"
}

###

GET http://localhost:8080/api/v1/employees
Accept: application/json

###

GET http://localhost:8080/api/v1/employees/1
Accept: application/json

###

PUT http://localhost:8080/api/v1/employees/2
Content-Type: application/json

{
  "firstName": "Hemant",
  "lastName": "Dwivedi",
  "email": "hk123@gmail.com",
  "phone": "1010109090",
  "dob": "31-01-1999",
  "gender": "male",
  "city": "patna",
  "state": "bihar",
  "pinCode": "845432"
}

###

DELETE http://localhost:8080/api/v1/employees/1

###