server:
  port: 8085
spring:
  application:
    name: training-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:training_db
    username: sa
    password:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# eureka config
eureka:
  instance:
    client:
      serverURL:
        defaultZone: http://localhost:8761/eureka/
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true